### ISSUE TITLE
Value Error COM method call without VTable

### ISSUE THREAD

**Issue by KillerBOSS2019** [AndreMiras/pycaw#68]
- OS version Win 11 Pro
- architecture 64bit
- Python version 3.9.6
- pycaw version v20220416
- exact stacktrace / accurate error message
```
Traceback (most recent call last):
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\__init__.py", line 912, in __del__
    self.Release()
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\__init__.py", line 1166, in Release
    return self.__com_Release()
ValueError: COM method call without VTable
```

**Comment by KillerBOSS2019** [comment]
No clue where it happens because It doesn't tell

**Comment by KillerBOSS2019** [comment]
[error.txt](https://github.com/AndreMiras/pycaw/files/8792789/error.txt)
Idk if this helps or not

**Comment by KillerBOSS2019** [comment]
```
C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\pycaw\utils.py:225: UserWarning: COMError attempting to get property 71 from device <POINTER(IMMDevice) ptr=0x1944d0b5680 at 192829e4440>: COMError(-2147024882, 'Not enough memory resources are available to complete this operation.', (None, None, None, 0, None))
  warnings.warn(
C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\pycaw\utils.py:225: UserWarning: COMError attempting to get property 72 from device <POINTER(IMMDevice) ptr=0x1944d0b5680 at 192829e4440>: COMError(-2147024882, 'Not enough memory resources are available to complete this operation.', (None, None, None, 0, None))
  warnings.warn(
11:53:03.964 [D] [__init__.py:911] Release <POINTER(IPropertyStore) ptr=0x192f346db60 at 192829e4e40>
11:53:03.965 [D] [__init__.py:911] Release <POINTER(IMMDevice) ptr=0x1944d0b5680 at 192829e4440>
11:53:03.967 [D] [_comobject.py:575] <pycaw.magic._MagicRootSession object at 0x00000192FFFBA370>.AddRef() -> 2
11:53:03.968 [D] [_comobject.py:575] <pycaw.magic._MagicRootSession object at 0x00000192FFFBA370>.AddRef() -> 3
wallpaper32.exe is an Active Session
11:53:03.968 [D] [_comobject.py:591] <pycaw.magic._MagicRootSession object at 0x00000192FFFBA370>.Release() -> 2
11:53:03.969 [D] [_comobject.py:591] <pycaw.magic._MagicRootSession object at 0x00000192FFFBA370>.Release() -> 1
11:53:03.982 [D] [__init__.py:911] Release <POINTER(IPropertyStore) ptr=0x192f346ccc0 at 192829e4440>
11:53:03.998 [D] [__init__.py:911] Release <POINTER(IPropertyStore) ptr=0x192f346ccc0 at 192829e43c0>
11:53:04.011 [D] [__init__.py:911] Release <POINTER(IPropertyStore) ptr=0x192f34704d0 at 192829e4e40>
11:53:04.027 [D] [__init__.py:911] Release <POINTER(IPropertyStore) ptr=0x192f34704d0 at 192829e4040>
11:53:04.028 [D] [__init__.py:911] Release <POINTER(IMMDeviceEnumerator) ptr=0x192f31bc850 at 192829e41c0>
11:53:04.028 [D] [__init__.py:911] Release <POINTER(IMMDeviceCollection) ptr=0x194491701f0 at 192829e48c0>
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\comtypes\_comobject.py", line 148, in call_without_this
    result = mth(*inargs)
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\pycaw\magic.py", line 199, in OnSessionCreated
    magic_root_session = _MagicRootSession(ctl, iid, cls)
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\pycaw\magic.py", line 616, in __init__
    self.app_exec = self._get_app_exec()
  File "C:\Users\Damie\AppData\Local\Programs\Python\Python39\lib\site-packages\pycaw\magic.py", line 807, in _get_app_exec
    self.pid = self._ctl2.GetProcessId()
_ctypes.COMError: (-2004287484, None, (None, None, None, 0, None))
11:53:04.176 [D] [__init__.py:911] Release <POINTER(ICreateErrorInfo) ptr=0x1944d0b2608 at 192829e43c0>
11:53:04.177 [D] [__init__.py:911] Release <POINTER(IAudioSessionControl) ptr=0x192f34b1b90 at 192829e4540>
11:53:04.177 [D] [_comobject.py:591] <pycaw.magic.MagicManager object at 0x00000192FFFBAF70>.Release() -> 2
11:53:04.177 [D] [_comobject.py:591] <pycaw.magic.MagicManager object at 0x00000192FFFBAF70>.Release() -> 1
```

**Comment by KillerBOSS2019** [comment]
solved

**Comment by RayRay10460** [comment]
Hi, how you solve the issue.

**Comment by KillerBOSS2019** [comment]
@RayRay10460 I solved by releasing the COM object I didn't realize that I had to call it manually.

**Comment by TJ-59** [comment]
@KillerBOSS2019 Could you give an example of which object and what function you use to release that COM object ?
I'm facing the same sort of issue when releasing callbacks, getting a python crash (which showed the same error after lengthy debugging) despite the fact I am, effectively, trying to unregister them...
(so, to me, it's like _"You have an error when trying to release that callback, you should instead release that callback, but since you didn't release that callback, here is this error message instead"_ self-eating ouroboros error...)
I've done it with the session's `unregister_notification`, the `._ctl`'s  `Release` and `UnregisterAudioSessionNotification`, but I keep getting these crash after a specific amount of actions (specific to the current program config, repeatable results).
Also, this can happen when actually adding new callbacks (to new session objects) or when trying to release old callbacks before deleting old session objects that aren't needed anymore.

**Comment by DamienStaebler** [comment]
For me I just release any COM object i created. On the object there should be ".release()" method

**Comment by TJ-59** [comment]
So, the control session of the audio session (aka `._ctl`) as in AudioSess._ctl.Release() (which I, somehow, happen to have to use twice to reach 0 —No idea why though—), but what function do you use for the callback itself ? Since I suppose, the callback too (inheriting from `AudioSessionEvents`) should be released ? (They seem to have inherited a `IUnknown_Release()` method, but I'm not too sure of the arguments, I guess a reference to itself is needed)
For the session manager and everything involved during the use of `AudioUtilities.GetAllSession()`, my guess is that it is already done internally, or it would be a problem for all pycaw users.

Thanks for the answers :)

**Comment by DamienStaebler** [comment]
I know that AudioSession class had mem leak because something it wasn't cleared. but I have made PR and approved. so that should be solved. Do you have repo that I can take a look?
